export const areaToCountryCode = {
  Afghan: "af",
  Albanian: "al",
  Algerian: "dz",
  Andorran: "ad",
  Angolan: "ao",
  "Antiguan, Barbudan": "ag",
  Argentine: "ar",
  Armenian: "am",
  Aruban: "aw",
  Australian: "au",
  Austrian: "at",
  Azerbaijani: "az",
  Bahamian: "bs",
  Bahraini: "bh",
  Bangladeshi: "bd",
  Barbadian: "bb",
  Belarusian: "by",
  Belgian: "be",
  Belizean: "bz",
  Beninese: "bj",
  Bermudian: "bm",
  Bhutanese: "bt",
  Bolivian: "bo",
  "Bosnian, Herzegovinian": "ba",
  Motswana: "bw",
  Brazilian: "br",
  British: "gb",
  Bruneian: "bn",
  Bulgarian: "bg",
  Burkinabe: "bf",
  Burmese: "mm",
  Burundian: "bi",
  Cambodian: "kh",
  Cameroonian: "cm",
  Canadian: "ca",
  "Cape Verdian": "cv",
  Caymanian: "ky",
  "Central African": "cf",
  Chadian: "td",
  "Channel Islander": "je",
  Chilean: "cl",
  Chinese: "cn",
  Colombian: "co",
  Congolese: "cd",
  "Costa Rican": "cr",
  Croatian: "hr",
  Cuban: "cu",
  Cypriot: "cy",
  Czech: "cz",
  Danish: "dk",
  Djibouti: "dj",
  Dominican: "do",
  Dutch: "nl",
  Ecuadorean: "ec",
  Egyptian: "eg",
  Emirati: "ae",
  "Equatorial Guinean": "gq",
  Eritrean: "er",
  Estonian: "ee",
  Ethiopian: "et",
  Faroese: "fo",
  Fijian: "fj",
  Filipino: "ph",
  Finnish: "fi",
  French: "fr",
  Gabonese: "ga",
  Gambian: "gm",
  Georgian: "ge",
  German: "de",
  Ghanaian: "gh",
  Gibraltar: "gi",
  Greek: "gr",
  Greenlandic: "gl",
  Grenadian: "gd",
  Guadeloupian: "gp",
  Guamanian: "gu",
  Guatemalan: "gt",
  Guinean: "gn",
  "Guinea-Bissauan": "gw",
  Guyanese: "gy",
  Haitian: "ht",
  Honduran: "hn",
  "Hong Konger": "hk",
  Hungarian: "hu",
  Icelander: "is",
  Indian: "in",
  Indonesian: "id",
  Iranian: "ir",
  Iraqi: "iq",
  Irish: "ie",
  Israeli: "il",
  Italian: "it",
  Ivorian: "ci",
  Jamaican: "jm",
  Japanese: "jp",
  Jordanian: "jo",
  Kazakhstani: "kz",
  Kenyan: "ke",
  Kirghiz: "kg",
  Kosovar: "xk",
  Kuwaiti: "kw",
  Laotian: "la",
  Latvian: "lv",
  Lebanese: "lb",
  Liberian: "lr",
  Libyan: "ly",
  Liechtensteiner: "li",
  Lithuanian: "lt",
  Luxembourger: "lu",
  Macedonian: "mk",
  Malagasy: "mg",
  Malawian: "mw",
  Malaysian: "my",
  Maldivan: "mv",
  Malian: "ml",
  Maltese: "mt",
  Mauritian: "mu",
  Mexican: "mx",
  Moldovan: "md",
  Mongolian: "mn",
  Montenegrin: "me",
  Moroccan: "ma",
  Mosotho: "ls",
  Mozambican: "mz",
  Namibian: "na",
  Nepalese: "np",
  "New Zealander": "nz",
  Nicaraguan: "ni",
  Nigerian: "ng",
  Nigerien: "ne",
  "Ni-Vanuatu": "vu",
  "North Korean": "kp",
  Norwegian: "no",
  Omani: "om",
  Pakistani: "pk",
  Palestinian: "ps",
  Panamanian: "pa",
  "Papua New Guinean": "pg",
  Paraguayan: "py",
  Peruvian: "pe",
  Polish: "pl",
  Portuguese: "pt",
  "Puerto Rican": "pr",
  Qatari: "qa",
  Romanian: "ro",
  Russian: "ru",
  Rwandan: "rw",
  "Saint Lucian": "lc",
  Salvadoran: "sv",
  Sammarinese: "sm",
  Samoan: "ws",
  "Saudi Arabian": "sa",
  Senegalese: "sn",
  Serbian: "rs",
  Seychellois: "sc",
  "Sierra Leonean": "sl",
  Singaporean: "sg",
  Slovak: "sk",
  Slovene: "si",
  "Solomon Islander": "sb",
  Somali: "so",
  "South African": "za",
  "South Korean": "kr",
  "South Sudanese": "ss",
  Spanish: "es",
  "Sri Lankan": "lk",
  Sudanese: "sd",
  Surinamer: "sr",
  Swedish: "se",
  Swiss: "ch",
  Syrian: "sy",
  Tadzhik: "tj",
  Taiwanese: "tw",
  Tanzanian: "tz",
  Thai: "th",
  Togolese: "tg",
  Tongan: "to",
  Trinidadian: "tt",
  Tunisian: "tn",
  Turkish: "tr",
  Turkmen: "tm",
  Tuvaluan: "tv",
  Ugandan: "ug",
  Ukrainian: "ua",
  American: "us",
  Uruguayan: "uy",
  Uzbekistani: "uz",
  Venezuelan: "ve",
  Vietnamese: "vn",
  Yemeni: "ye",
  Zambian: "zm",
  Zimbabwean: "zw"
};
